return {
  require "plugins.mason",
  require "plugins.avante",
  require "plugins.nvim-lspconfig",
  require "plugins.treesitter",
  require "plugins.ts-autotag",
  require "plugins.comment",
  require "plugins.todo",
  require "plugins.trouble",
  require "plugins.spectre",
  require "plugins.nvimtree",
  require "plugins.copilot",
  require "plugins.leetcode",
  require "plugins.conform",
}
